//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchasingDepartmentDobrinPtitsynYalunin4IS_29.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdProduct { get; set; }
        public int Quantity { get; set; }
        public int IdUnitOfMeasure { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int IdStatusDelivery { get; set; }
    
        public virtual Products1 Products1 { get; set; }
        public virtual StatusDelivery StatusDelivery { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual User User { get; set; }
    }
}
