//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchasingDepartmentDobrinPtitsynYalunin4IS_29.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products1
    {
        public Products1()
        {
            this.Order = new HashSet<Order>();
            this.Purchases = new HashSet<Purchases>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdCategory { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Purchases> Purchases { get; set; }
    }
}
