//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchasingDepartmentDobrinPtitsynYalunin4IS_29.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Order = new HashSet<Order>();
            this.Purchases = new HashSet<Purchases>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public int IdRole { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Purchases> Purchases { get; set; }
        public virtual Role Role { get; set; }
    }
}
